@startuml CannnonShooting ActivityMap
Title CannnonShooting ActivityMap

/'処理順のメモ
1  リソースの読み込み
2  エラーチェック
3  アプリケーションの立ち上げ(初期化)
4  エラーチェック
5  スタート画面へ移行
6  スタートシーンの初期化
7  エラーチェック
8  待機
9  スタートボタンが呼ばれた来夏の処理を走らせる
10 ロード画面を表示
11 リソースの読み込み・メモリに載せる
12 エラーチェック
13 メインシーンの初期化
14 エラーチェック
15 制限時間カウント開始

-------------制限時間終了まで以下コマンドベースで駆動----------------
移動ボタンが押されたら大砲の弾を動かす
発射ボタンが押されたら大砲を生成する
→ 生成された大砲の弾は決まった方向へ飛んでいく

大砲の弾と敵の衝突判定
→ 爆発エフェクト
→ 衝突したら敵のHPを減らす

エラーチェック 
yes エラーダイアログを出して更新停止 スタートメニュー画面へ移行
no そのまま処理を続行
'/
'=================================================================
start
:アプリケーションの初期化(fps, 解像度);
if(<color:red>エラーチェック) then(yes)
    :エラー通知(ダイアログ);
    :エラーステータスへ移行;
else (no)
    :メインシーン読み込み;

    if(<color:red>エラーチェック)then(yes)
    :エラー通知(ダイアログ);
    :エラーステータスへ移行;
endif

stop
'================================================================

@enduml