@startuml CannonShooting
title CannonShooting ClassMap

//オブジェクト指向のポイント
// ドメイン(業務の関心事)のデータとロジックを一緒にしてオブジェクト単位でまとめる技法
// 手続き型はトップダウン、オブジェクト指向はパーツを作って関係を構築していくボトムアップ

//1登場人物の整理 (業務の関心事を洗い出す)
// ヒト(業務活動の当事者)：プレイヤー・敵
// モノ(人が業務を遂行するときの関心の対象)：大砲・大砲の弾・エネミー、制限時間・スコア・入力・HP
// コト(事象)：大砲とエネミーの衝突、大砲の弾とエネミーの衝突

//2各々の関心事を説明する

// 大砲
// 回転






@enduml